[2021-01-22 12:05:37,081] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: connection_snowflake.get_count 2021-01-22T11:05:22.880096+00:00 [queued]>
[2021-01-22 12:05:37,088] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: connection_snowflake.get_count 2021-01-22T11:05:22.880096+00:00 [queued]>
[2021-01-22 12:05:37,088] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-22 12:05:37,088] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-22 12:05:37,088] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-22 12:05:37,097] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): get_count> on 2021-01-22T11:05:22.880096+00:00
[2021-01-22 12:05:37,101] {standard_task_runner.py:51} INFO - Started process 4695 to run task
[2021-01-22 12:05:37,113] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'connection_snowflake', 'get_count', '2021-01-22T11:05:22.880096+00:00', '--job-id', '27', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/connection_snowflake_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmpg3i2hlh9']
[2021-01-22 12:05:37,116] {standard_task_runner.py:76} INFO - Job 27: Subtask get_count
[2021-01-22 12:05:37,155] {logging_mixin.py:103} INFO - Running <TaskInstance: connection_snowflake.get_count 2021-01-22T11:05:22.880096+00:00 [running]> on host admins-air.home
[2021-01-22 12:05:37,186] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=connection_snowflake
AIRFLOW_CTX_TASK_ID=get_count
AIRFLOW_CTX_EXECUTION_DATE=2021-01-22T11:05:22.880096+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-01-22T11:05:22.880096+00:00
[2021-01-22 12:05:37,196] {base.py:65} INFO - Using connection to: id: snowflake_conn. Host: dp13486.eu-west-1.snowflakecomputing.com, Port: None, Schema: PUBLIC, Login: SARA, Password: XXXXXXXX, extra: XXXXXXXX
[2021-01-22 12:05:37,200] {connection.py:215} INFO - Snowflake Connector for Python Version: 2.3.8, Python Version: 3.8.6, Platform: macOS-10.16-x86_64-i386-64bit
[2021-01-22 12:05:37,201] {connection.py:768} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2021-01-22 12:05:37,201] {connection.py:784} INFO - Setting use_openssl_only mode to False
[2021-01-22 12:05:38,198] {cursor.py:537} INFO - query: [select count(*) from public.test_employee]
[2021-01-22 12:05:38,427] {cursor.py:560} INFO - query execution done
[2021-01-22 12:05:38,450] {connection.py:438} INFO - closed
[2021-01-22 12:05:38,577] {connection.py:441} INFO - No async queries seem to be running, deleting session
[2021-01-22 12:05:38,726] {connection_snowflake_dag.py:59} INFO - Number of rows in `public.test_employee`  - 3
[2021-01-22 12:05:38,727] {python.py:118} INFO - Done. Returned value was: None
[2021-01-22 12:05:38,733] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=connection_snowflake, task_id=get_count, execution_date=20210122T110522, start_date=20210122T110537, end_date=20210122T110538
[2021-01-22 12:05:38,748] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-01-22 12:05:38,781] {local_task_job.py:118} INFO - Task exited with return code 0
