[2021-01-24 18:29:27,106] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_snowflake_dag.ge_val_01 2021-01-23T11:11:25.299548+00:00 [queued]>
[2021-01-24 18:29:27,112] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_snowflake_dag.ge_val_01 2021-01-23T11:11:25.299548+00:00 [queued]>
[2021-01-24 18:29:27,112] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-24 18:29:27,112] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-24 18:29:27,112] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-24 18:29:27,119] {taskinstance.py:1038} INFO - Executing <Task(GreatExpectationsOperator): ge_val_01> on 2021-01-23T11:11:25.299548+00:00
[2021-01-24 18:29:27,122] {standard_task_runner.py:51} INFO - Started process 15666 to run task
[2021-01-24 18:29:27,131] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_snowflake_dag', 'ge_val_01', '2021-01-23T11:11:25.299548+00:00', '--job-id', '32', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_snowflake_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmpwg93lgfc']
[2021-01-24 18:29:27,132] {standard_task_runner.py:76} INFO - Job 32: Subtask ge_val_01
[2021-01-24 18:29:27,166] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_snowflake_dag.ge_val_01 2021-01-23T11:11:25.299548+00:00 [running]> on host admins-air.home
[2021-01-24 18:29:27,192] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_snowflake_dag
AIRFLOW_CTX_TASK_ID=ge_val_01
AIRFLOW_CTX_EXECUTION_DATE=2021-01-23T11:11:25.299548+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-23T11:11:25.299548+00:00
[2021-01-24 18:29:27,193] {great_expectations.py:94} INFO - Running validation with Great Expectations...
[2021-01-24 18:29:27,216] {connection.py:215} INFO - Snowflake Connector for Python Version: 2.3.8, Python Version: 3.8.6, Platform: macOS-10.16-x86_64-i386-64bit
[2021-01-24 18:29:27,217] {connection.py:768} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2021-01-24 18:29:27,217] {connection.py:784} INFO - Setting use_openssl_only mode to False
[2021-01-24 18:29:28,581] {local_task_job.py:118} INFO - Task exited with return code Negsignal.SIGSEGV
