[2021-02-17 12:06:14,592] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_demo_db_dag.check_expectation_suite 2021-02-17T11:06:06.446863+00:00 [queued]>
[2021-02-17 12:06:14,602] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_demo_db_dag.check_expectation_suite 2021-02-17T11:06:06.446863+00:00 [queued]>
[2021-02-17 12:06:14,602] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-02-17 12:06:14,602] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-02-17 12:06:14,602] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-02-17 12:06:14,610] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): check_expectation_suite> on 2021-02-17T11:06:06.446863+00:00
[2021-02-17 12:06:14,613] {standard_task_runner.py:51} INFO - Started process 11601 to run task
[2021-02-17 12:06:14,624] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_demo_db_dag', 'check_expectation_suite', '2021-02-17T11:06:06.446863+00:00', '--job-id', '507', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_demo_db_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmpl2ea9tzq']
[2021-02-17 12:06:14,628] {standard_task_runner.py:76} INFO - Job 507: Subtask check_expectation_suite
[2021-02-17 12:06:14,671] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_demo_db_dag.check_expectation_suite 2021-02-17T11:06:06.446863+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-02-17 12:06:14,711] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_demo_db_dag
AIRFLOW_CTX_TASK_ID=check_expectation_suite
AIRFLOW_CTX_EXECUTION_DATE=2021-02-17T11:06:06.446863+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-17T11:06:06.446863+00:00
[2021-02-17 12:06:14,712] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T
[2021-02-17 12:06:14,713] {bash.py:158} INFO - Running command: cd /Users/sara/airflow/dags/snowflake/ge_demo_db && great_expectations docs build -y
[2021-02-17 12:06:14,725] {bash.py:169} INFO - Output:
[2021-02-17 12:06:18,490] {bash.py:173} INFO - Detected legacy config version (2.0) so will try to use default checkpoint store name.
[2021-02-17 12:06:18,491] {bash.py:173} INFO -   Please update your configuration to the new version number 3.0 in order to use the new "Checkpoint Store" feature.  Visit https://docs.greatexpectations.io/en/latest/how_to_guides/migrating_versions.html to learn more about the upgrade process.
[2021-02-17 12:06:18,563] {bash.py:173} INFO - Detected legacy config version (2.0) so will try to use default checkpoint store name.
[2021-02-17 12:06:18,564] {bash.py:173} INFO -   Please update your configuration to the new version number 3.0 in order to use the new "Checkpoint Store" feature.  Visit https://docs.greatexpectations.io/en/latest/how_to_guides/migrating_versions.html to learn more about the upgrade process.
[2021-02-17 12:06:18,640] {bash.py:173} INFO - Detected legacy config version (2.0) so will try to use default checkpoint store name.
[2021-02-17 12:06:18,640] {bash.py:173} INFO -   Please update your configuration to the new version number 3.0 in order to use the new "Checkpoint Store" feature.  Visit https://docs.greatexpectations.io/en/latest/how_to_guides/migrating_versions.html to learn more about the upgrade process.
[2021-02-17 12:06:20,289] {bash.py:173} INFO - 
[2021-02-17 12:06:20,289] {bash.py:173} INFO - The following Data Docs sites will be built:
[2021-02-17 12:06:20,290] {bash.py:173} INFO - 
[2021-02-17 12:06:20,290] {bash.py:173} INFO -  - local_site: file:///Users/sara/airflow/dags/snowflake/ge_demo_db/great_expectations/uncommitted/data_docs/local_site/index.html
[2021-02-17 12:06:20,290] {bash.py:173} INFO - 
[2021-02-17 12:06:20,291] {bash.py:173} INFO - 
[2021-02-17 12:06:20,291] {bash.py:173} INFO - Building Data Docs...
[2021-02-17 12:06:20,292] {bash.py:173} INFO - 
[2021-02-17 12:06:20,835] {bash.py:173} INFO - Done building Data Docs
[2021-02-17 12:06:22,497] {bash.py:177} INFO - Command exited with return code 0
[2021-02-17 12:06:22,561] {taskinstance.py:1285} ERROR - Failed when executing success callback
[2021-02-17 12:06:22,566] {taskinstance.py:1286} ERROR - <lambda>() takes 0 positional arguments but 1 was given
Traceback (most recent call last):
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1283, in _run_success_callback
    task.on_success_callback(context)
TypeError: <lambda>() takes 0 positional arguments but 1 was given
[2021-02-17 12:06:22,584] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=ge_demo_db_dag, task_id=check_expectation_suite, execution_date=20210217T110606, start_date=20210217T110614, end_date=20210217T110622
[2021-02-17 12:06:22,658] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-02-17 12:06:22,680] {local_task_job.py:118} INFO - Task exited with return code 0
