[2021-02-02 10:11:11,565] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.Val_monthlychk 2021-02-02T09:10:51.738858+00:00 [queued]>
[2021-02-02 10:11:11,570] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.Val_monthlychk 2021-02-02T09:10:51.738858+00:00 [queued]>
[2021-02-02 10:11:11,570] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-02-02 10:11:11,570] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-02-02 10:11:11,571] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-02-02 10:11:11,578] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): Val_monthlychk> on 2021-02-02T09:10:51.738858+00:00
[2021-02-02 10:11:11,581] {standard_task_runner.py:51} INFO - Started process 2455 to run task
[2021-02-02 10:11:11,589] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_quarantine_df_dag', 'Val_monthlychk', '2021-02-02T09:10:51.738858+00:00', '--job-id', '273', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_quarantine_df_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmpd8bwddor']
[2021-02-02 10:11:11,591] {standard_task_runner.py:76} INFO - Job 273: Subtask Val_monthlychk
[2021-02-02 10:11:11,628] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_quarantine_df_dag.Val_monthlychk 2021-02-02T09:10:51.738858+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-02-02 10:11:11,662] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_quarantine_df_dag
AIRFLOW_CTX_TASK_ID=Val_monthlychk
AIRFLOW_CTX_EXECUTION_DATE=2021-02-02T09:10:51.738858+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-02T09:10:51.738858+00:00
[2021-02-02 10:11:11,663] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T
[2021-02-02 10:11:11,664] {bash.py:158} INFO - Running command: cd /Users/sara/airflow/dags/demo && great_expectations checkpoint run monthlychk
[2021-02-02 10:11:11,675] {bash.py:169} INFO - Output:
[2021-02-02 10:11:14,741] {bash.py:173} INFO - Heads up! This feature is Experimental. It may change. Please give us your feedback!
[2021-02-02 10:11:14,775] {bash.py:173} INFO - You appear to be using a legacy capability with the latest config version (3.0).
[2021-02-02 10:11:14,776] {bash.py:173} INFO -     Your data context with this configuration version uses validation_operators, which are being deprecated.  Please update your configuration to be compatible with the version number 3.
[2021-02-02 10:11:27,903] {bash.py:173} INFO - Validation succeeded!
[2021-02-02 10:11:27,913] {bash.py:173} INFO - 
[2021-02-02 10:11:27,914] {bash.py:173} INFO - Suite Name                                   Status     Expectations met
[2021-02-02 10:11:27,914] {bash.py:173} INFO - - taxisuite                                  âœ” Passed   13 of 13 (100.0 %)
[2021-02-02 10:11:28,721] {bash.py:177} INFO - Command exited with return code 0
[2021-02-02 10:11:28,743] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=ge_quarantine_df_dag, task_id=Val_monthlychk, execution_date=20210202T091051, start_date=20210202T091111, end_date=20210202T091128
[2021-02-02 10:11:28,768] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-02-02 10:11:28,806] {local_task_job.py:118} INFO - Task exited with return code 0
