[2021-01-21 13:04:24,504] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_local_dag.ge_val_02 2021-01-21T12:03:51.043362+00:00 [queued]>
[2021-01-21 13:04:24,513] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_local_dag.ge_val_02 2021-01-21T12:03:51.043362+00:00 [queued]>
[2021-01-21 13:04:24,514] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-21 13:04:24,514] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-21 13:04:24,514] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-21 13:04:24,523] {taskinstance.py:1038} INFO - Executing <Task(GreatExpectationsOperator): ge_val_02> on 2021-01-21T12:03:51.043362+00:00
[2021-01-21 13:04:24,529] {standard_task_runner.py:51} INFO - Started process 16668 to run task
[2021-01-21 13:04:24,540] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_local_dag', 'ge_val_02', '2021-01-21T12:03:51.043362+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_local_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmpl9ce6uiw']
[2021-01-21 13:04:24,541] {standard_task_runner.py:76} INFO - Job 6: Subtask ge_val_02
[2021-01-21 13:04:24,581] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_local_dag.ge_val_02 2021-01-21T12:03:51.043362+00:00 [running]> on host admins-air.home
[2021-01-21 13:04:24,612] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_local_dag
AIRFLOW_CTX_TASK_ID=ge_val_02
AIRFLOW_CTX_EXECUTION_DATE=2021-01-21T12:03:51.043362+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-01-21T12:03:51.043362+00:00
[2021-01-21 13:04:24,613] {great_expectations.py:94} INFO - Running validation with Great Expectations...
[2021-01-21 13:04:24,721] {data_context.py:1215} INFO - Setting run_name to: 20210121T120424.720773Z
[2021-01-21 13:04:24,724] {data_asset.py:636} INFO - 	14 expectation(s) included in expectation_suite.
[2021-01-21 13:04:25,960] {great_expectations.py:135} INFO - Validation with Great Expectations successful.
[2021-01-21 13:04:25,967] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=ge_local_dag, task_id=ge_val_02, execution_date=20210121T120351, start_date=20210121T120424, end_date=20210121T120425
[2021-01-21 13:04:26,074] {local_task_job.py:118} INFO - Task exited with return code 1
