[2021-01-25 09:00:01,926] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_bash_op_dag.export_to_generic_table 2021-01-25T07:59:16.516080+00:00 [queued]>
[2021-01-25 09:00:01,933] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_bash_op_dag.export_to_generic_table 2021-01-25T07:59:16.516080+00:00 [queued]>
[2021-01-25 09:00:01,933] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-25 09:00:01,933] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-25 09:00:01,933] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-25 09:00:01,939] {taskinstance.py:1038} INFO - Executing <Task(SnowflakeOperator): export_to_generic_table> on 2021-01-25T07:59:16.516080+00:00
[2021-01-25 09:00:01,943] {standard_task_runner.py:51} INFO - Started process 4505 to run task
[2021-01-25 09:00:01,950] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_bash_op_dag', 'export_to_generic_table', '2021-01-25T07:59:16.516080+00:00', '--job-id', '54', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_bash_op_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmp8b7bb2_6']
[2021-01-25 09:00:01,952] {standard_task_runner.py:76} INFO - Job 54: Subtask export_to_generic_table
[2021-01-25 09:00:01,988] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_bash_op_dag.export_to_generic_table 2021-01-25T07:59:16.516080+00:00 [running]> on host admins-air.home
[2021-01-25 09:00:02,015] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_bash_op_dag
AIRFLOW_CTX_TASK_ID=export_to_generic_table
AIRFLOW_CTX_EXECUTION_DATE=2021-01-25T07:59:16.516080+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-01-25T07:59:16.516080+00:00
[2021-01-25 09:00:02,016] {snowflake.py:119} INFO - Executing: ['insert into  GENERIC_NYC_TAXI select * from NYC_TAXI_01;']
[2021-01-25 09:00:02,025] {base.py:65} INFO - Using connection to: id: SNOWFLAKE_CONN_DEMO. Host: dp13486.eu-west-1.snowflakecomputing.com, Port: None, Schema: PUBLIC, Login: SARA, Password: XXXXXXXX, extra: XXXXXXXX
[2021-01-25 09:00:02,029] {connection.py:215} INFO - Snowflake Connector for Python Version: 2.3.8, Python Version: 3.8.6, Platform: macOS-10.16-x86_64-i386-64bit
[2021-01-25 09:00:02,030] {connection.py:768} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2021-01-25 09:00:02,031] {connection.py:784} INFO - Setting use_openssl_only mode to False
[2021-01-25 09:00:03,827] {cursor.py:537} INFO - query: [ALTER SESSION SET autocommit=True]
[2021-01-25 09:00:04,441] {cursor.py:560} INFO - query execution done
[2021-01-25 09:00:04,442] {dbapi.py:180} INFO - Running statement: insert into  GENERIC_NYC_TAXI select * from NYC_TAXI_01;, parameters: None
[2021-01-25 09:00:04,443] {cursor.py:537} INFO - query: [insert into  GENERIC_NYC_TAXI select * from NYC_TAXI_01;]
[2021-01-25 09:00:06,388] {cursor.py:560} INFO - query execution done
[2021-01-25 09:00:06,390] {dbapi.py:186} INFO - Rows affected: 10000
[2021-01-25 09:00:06,391] {connection.py:438} INFO - closed
[2021-01-25 09:00:06,459] {connection.py:441} INFO - No async queries seem to be running, deleting session
[2021-01-25 09:00:06,567] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=ge_bash_op_dag, task_id=export_to_generic_table, execution_date=20210125T075916, start_date=20210125T080001, end_date=20210125T080006
[2021-01-25 09:00:06,583] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-01-25 09:00:06,612] {local_task_job.py:118} INFO - Task exited with return code 0
