[2021-02-17 11:58:27,894] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_demo_db_dag.check_expectation_suite 2021-02-17T10:58:02.726211+00:00 [queued]>
[2021-02-17 11:58:27,908] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_demo_db_dag.check_expectation_suite 2021-02-17T10:58:02.726211+00:00 [queued]>
[2021-02-17 11:58:27,908] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-02-17 11:58:27,908] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-02-17 11:58:27,908] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-02-17 11:58:27,925] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): check_expectation_suite> on 2021-02-17T10:58:02.726211+00:00
[2021-02-17 11:58:27,931] {standard_task_runner.py:51} INFO - Started process 11201 to run task
[2021-02-17 11:58:27,946] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_demo_db_dag', 'check_expectation_suite', '2021-02-17T10:58:02.726211+00:00', '--job-id', '504', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_demo_db_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmp9riug5mi']
[2021-02-17 11:58:27,949] {standard_task_runner.py:76} INFO - Job 504: Subtask check_expectation_suite
[2021-02-17 11:58:28,042] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_demo_db_dag.check_expectation_suite 2021-02-17T10:58:02.726211+00:00 [running]> on host admins-macbook-air.local
[2021-02-17 11:58:28,108] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_demo_db_dag
AIRFLOW_CTX_TASK_ID=check_expectation_suite
AIRFLOW_CTX_EXECUTION_DATE=2021-02-17T10:58:02.726211+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-17T10:58:02.726211+00:00
[2021-02-17 11:58:28,109] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T
[2021-02-17 11:58:28,112] {bash.py:158} INFO - Running command: cd /Users/sara/airflow/dags/snowflake/ge_demo_db && great_expectations docs build -y
[2021-02-17 11:58:28,131] {bash.py:169} INFO - Output:
[2021-02-17 11:58:39,993] {bash.py:173} INFO - Detected legacy config version (2.0) so will try to use default checkpoint store name.
[2021-02-17 11:58:39,998] {bash.py:173} INFO -   Please update your configuration to the new version number 3.0 in order to use the new "Checkpoint Store" feature.  Visit https://docs.greatexpectations.io/en/latest/how_to_guides/migrating_versions.html to learn more about the upgrade process.
[2021-02-17 11:58:40,276] {bash.py:173} INFO - Detected legacy config version (2.0) so will try to use default checkpoint store name.
[2021-02-17 11:58:40,277] {bash.py:173} INFO -   Please update your configuration to the new version number 3.0 in order to use the new "Checkpoint Store" feature.  Visit https://docs.greatexpectations.io/en/latest/how_to_guides/migrating_versions.html to learn more about the upgrade process.
[2021-02-17 11:58:40,430] {bash.py:173} INFO - Detected legacy config version (2.0) so will try to use default checkpoint store name.
[2021-02-17 11:58:40,431] {bash.py:173} INFO -   Please update your configuration to the new version number 3.0 in order to use the new "Checkpoint Store" feature.  Visit https://docs.greatexpectations.io/en/latest/how_to_guides/migrating_versions.html to learn more about the upgrade process.
[2021-02-17 11:58:42,788] {bash.py:173} INFO - 
[2021-02-17 11:58:42,789] {bash.py:173} INFO - The following Data Docs sites will be built:
[2021-02-17 11:58:42,790] {bash.py:173} INFO - 
[2021-02-17 11:58:42,791] {bash.py:173} INFO -  - local_site: file:///Users/sara/airflow/dags/snowflake/ge_demo_db/great_expectations/uncommitted/data_docs/local_site/index.html
[2021-02-17 11:58:42,791] {bash.py:173} INFO - 
[2021-02-17 11:58:42,792] {bash.py:173} INFO - 
[2021-02-17 11:58:42,793] {bash.py:173} INFO - Building Data Docs...
[2021-02-17 11:58:42,794] {bash.py:173} INFO - 
[2021-02-17 11:58:47,556] {bash.py:173} INFO - Done building Data Docs
[2021-02-17 11:58:51,639] {bash.py:177} INFO - Command exited with return code 0
[2021-02-17 11:58:51,681] {taskinstance.py:1285} ERROR - Failed when executing success callback
[2021-02-17 11:58:51,683] {taskinstance.py:1286} ERROR - <lambda>() takes 0 positional arguments but 1 was given
Traceback (most recent call last):
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1283, in _run_success_callback
    task.on_success_callback(context)
TypeError: <lambda>() takes 0 positional arguments but 1 was given
[2021-02-17 11:58:51,689] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=ge_demo_db_dag, task_id=check_expectation_suite, execution_date=20210217T105802, start_date=20210217T105827, end_date=20210217T105851
[2021-02-17 11:58:51,865] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-02-17 11:58:51,924] {local_task_job.py:118} INFO - Task exited with return code 0
